
project_id = "xsalkjgevllriluawvcp"

[api]
enabled = true

[[api.schemas]]
name = "public"

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[edge_functions]
enabled = true

[[edge_functions.routes]]
path = "/eventos"
function = "eventos"

[[edge_functions.routes]]
path = "/eventos/*"
function = "eventos"

[[edge_functions.routes]]
path = "/convites/*"
function = "convites"

[[edge_functions.routes]]
path = "/convites/importar/*"
function = "convites"

[[edge_functions.routes]]
path = "/audit-log"
function = "audit-log"

[[edge_functions.routes]]
path = "/audit-log-batch"
function = "audit-log-batch"
