
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsalkjgevllriluawvcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzYWxramdldmxscmlsdWF3dmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDQzNDksImV4cCI6MjA2MTUyMDM0OX0.fKj5sJRgJBlDN3XsYWSTqexv4lk8N4tTBdyrIM2ubJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
